services:
  taskmanager:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: flink.Dockerfile
    container_name: taskmanager
    hostname: taskmanager
    user: "${UID}:${GID}"
    depends_on:
      - jobmanager
    command: /opt/flink/bin/taskmanager.sh start-foreground
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 6
      - JUICEFS_META_URL=redis://redis:6379/1
      - JUICEFS_STORAGE=s3
      - JUICEFS_BUCKET=my-juicefs-bucket
      - JUICEFS_ACCESS_KEY=${JUICEFS_ACCESS_KEY}
      - JUICEFS_SECRET_KEY=${JUICEFS_SECRET_KEY}
    volumes:
      - ./src/usrcode:/opt/flink/usrcode
      - juicefs_mount:/mnt/jfs

  jobmanager:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: flink.Dockerfile
    container_name: jobmanager
    hostname: jobmanager
    user: "${UID}:${GID}"
    ports:
      - "8081:8081"
    command: /opt/flink/bin/jobmanager.sh start-foreground
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager
        rest.port: 8082
      - JUICEFS_META_URL=redis://redis:6379/1
      - JUICEFS_STORAGE=s3
      - JUICEFS_BUCKET=my-juicefs-bucket
      - JUICEFS_ACCESS_KEY=AKIA6JKEYBLHOLKMTR7B
      - JUICEFS_SECRET_KEY=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
    volumes:
      - ./src/usrcode:/opt/flink/usrcode
      - juicefs_mount:/mnt/jfs

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "rail_network:1:1,output-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redis_data:
  juicefs_mount:
